version: "3.8"
services:
  postgres_user:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env.example
    ports:
      - "8081:8081"
    depends_on:
      - postgres_user
      - redis
  product-service:
    build: ./product-service
    env_file:
      - ./product-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - postgres_user
      - redis
  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    ports:
      - "8083:8083"
    depends_on:
      - postgres_user
  chatbot-service:
    build: ./chatbot-service
    env_file:
      - ./chatbot-service/.env
    ports:
      - "8084:8084"
    depends_on:
      - order-service
volumes:
  postgres_user_data:
  redis_data:
