openapi: 3.0.0
info:
  title: Order Service API
  version: 1.0.0
paths:
  /orders:
    post:
      summary: Create a new order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateRequest"
      responses:
        "201":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
    get:
      summary: List all orders (admin only)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of all orders
        "403":
          description: Forbidden
  /orders/my-orders:
    get:
      summary: List my orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "401":
          description: Unauthorized
  /orders/{id}:
    get:
      summary: Get order by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
  /orders/{id}/confirm-ready:
    put:
      summary: Partner confirms order ready for delivery
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Order marked as ready
        "403":
          description: Forbidden
  /orders/{id}/confirm-delivery:
    put:
      summary: Buyer confirms order delivered
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Order marked as delivered
        "403":
          description: Forbidden
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        total_amount:
          type: number
        status:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
        commission:
          type: number
    OrderItem:
      type: object
      properties:
        id:
          type: string
        order_id:
          type: string
        product_id:
          type: string
        quantity:
          type: integer
        unit_price:
          type: number
    OrderCreateRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: string
              quantity:
                type: integer
